import type { Locale } from "@/lib/locale";

const copy = {
  en: {
    updatesTitle: "Batch updates",
    employeeLead: "Propose a quantity or growth-stage change. Your supervisor reviews it before the batch changes.",
    supervisorLead: "Review field proposals. Approving updates the batch. It does not complete the employee’s tasks.",
    submit: "Submit batch update",
    submitting: "Submitting…",
    resubmit: "Resubmit for review",
    resubmitting: "Resubmitting…",
    approve: "Approve and update batch",
    reject: "Reject with this reason",
    revise: "Request changes",
    reviewing: "Saving decision…",
    feedback: "Reason for the employee",
    feedbackHint: "Required when you reject or request changes.",
    notes: "What changed",
    quantity: "Proposed quantity",
    stage: "Proposed stage",
    batch: "Batch",
    search: "Search batch, species, or person",
    sortNewest: "Newest",
    sortOldest: "Oldest",
    sortQty: "Largest quantity",
    empty: "Nothing in this status.",
    pending: "Pending review",
    revision: "Needs revision",
    approved: "Approved",
    rejected: "Rejected",
    all: "All",
    from: "From",
    to: "To",
    decisionBy: "Decision",
    yourNote: "Field note",
    supervisorNote: "Supervisor feedback",
    tasksUntouched: "Approval updates the batch only. Task completion stays a separate action.",
    record: "Record a batch update",
    awaiting: "Awaiting review",
    needsYou: "Needs your revision",
    reviewQueue: "Review batch updates",
  },
  ar: {
    updatesTitle: "تحديثات الدفعات",
    employeeLead: "اقترح تغيير الكمية أو مرحلة النمو. المشرف يراجع الطلب قبل أن تتغير الدفعة.",
    supervisorLead: "راجع مقترحات الحقل. الموافقة تحدّث الدفعة ولا تُكمل مهام الموظف.",
    submit: "إرسال تحديث الدفعة",
    submitting: "جارٍ الإرسال…",
    resubmit: "إعادة الإرسال للمراجعة",
    resubmitting: "جارٍ إعادة الإرسال…",
    approve: "موافقة وتحديث الدفعة",
    reject: "رفض مع هذا السبب",
    revise: "طلب تعديلات",
    reviewing: "جارٍ حفظ القرار…",
    feedback: "السبب للموظف",
    feedbackHint: "مطلوب عند الرفض أو طلب التعديل.",
    notes: "ما الذي تغيّر",
    quantity: "الكمية المقترحة",
    stage: "مرحلة النمو المقترحة",
    batch: "الدفعة",
    search: "ابحث عن الدفعة أو النوع أو الشخص",
    sortNewest: "الأحدث",
    sortOldest: "الأقدم",
    sortQty: "الأكبر كمية",
    empty: "لا يوجد شيء في هذه الحالة.",
    pending: "بانتظار المراجعة",
    revision: "يحتاج تعديلاً",
    approved: "موافق عليه",
    rejected: "مرفوض",
    all: "الكل",
    from: "من",
    to: "إلى",
    decisionBy: "القرار",
    yourNote: "ملاحظة الحقل",
    supervisorNote: "ملاحظة المشرف",
    tasksUntouched: "الموافقة تحدّث الدفعة فقط. إكمال المهمة إجراء منفصل.",
    record: "تسجيل تحديث دفعة",
    awaiting: "بانتظار المراجعة",
    needsYou: "يحتاج تعديلك",
    reviewQueue: "مراجعة تحديثات الدفعات",
  },
} as const;

export function workflowCopy(locale: Locale) {
  return copy[locale];
}

const navAr: Record<string, string> = {
  "/employee": "الرئيسية",
  "/employee/zone": "منطقتي",
  "/employee/tasks": "المهام",
  "/employee/monitoring": "القراءات",
  "/employee/alerts": "التنبيهات",
  "/employee/updates": "تحديثات الدفعات",
  "/employee/inventory": "المخزون",
  "/employee/history": "السجل",
  "/employee/profile": "الملف",
  "/supervisor": "نظرة عامة",
  "/supervisor/zones": "المناطق",
  "/supervisor/employees": "الفريق",
  "/supervisor/insights": "التقارير",
  "/supervisor/requests": "طلبات الشتلات",
  "/supervisor/updates": "تحديثات الدفعات",
  "/supervisor/alerts": "التنبيهات",
  "/supervisor/knowledge": "المعرفة",
  "/supervisor/profile": "الملف",
  "/hq": "الشبكة",
  "/hq/requests": "الطلبات",
  "/hq/reports": "التقارير",
  "/hq/production": "التخطيط",
  "/hq/alerts": "التنبيهات",
  "/hq/profile": "الملف",
};

export function navLabel(locale: Locale, href: string, fallback: string) {
  if (locale === "ar") return navAr[href] ?? fallback;
  return fallback;
}
